/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyCard {
        "userName": string;
    }
    interface MyComponent {
    }
    interface SkSearch {
        "searchText": string;
    }
}
declare global {
    interface HTMLMyCardElement extends Components.MyCard, HTMLStencilElement {
    }
    var HTMLMyCardElement: {
        prototype: HTMLMyCardElement;
        new (): HTMLMyCardElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSkSearchElement extends Components.SkSearch, HTMLStencilElement {
    }
    var HTMLSkSearchElement: {
        prototype: HTMLSkSearchElement;
        new (): HTMLSkSearchElement;
    };
    interface HTMLElementTagNameMap {
        "my-card": HTMLMyCardElement;
        "my-component": HTMLMyComponentElement;
        "sk-search": HTMLSkSearchElement;
    }
}
declare namespace LocalJSX {
    interface MyCard {
        "userName"?: string;
    }
    interface MyComponent {
    }
    interface SkSearch {
        "searchText"?: string;
    }
    interface IntrinsicElements {
        "my-card": MyCard;
        "my-component": MyComponent;
        "sk-search": SkSearch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-card": LocalJSX.MyCard & JSXBase.HTMLAttributes<HTMLMyCardElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "sk-search": LocalJSX.SkSearch & JSXBase.HTMLAttributes<HTMLSkSearchElement>;
        }
    }
}
